### ISSUE TITLE
Error al ejecutar la parte de cliente de sockets

### ISSUE THREAD

**Issue by KennetMP** [astuaTEC/Proyecto-Scrabble#1]
El error de una librería "cannot find -iGL" y "collect2: ld returned 1 exit:status"
imagen : https://drive.google.com/open?id=105f_hf1vR7T_65HQ4ux74ZevqRxCRyee

**Comment by KennetMP** [comment]
Error se resolvio corriendo el programa en otra computadora, siendo un error de librerías  instaladas

**Comment by TheACE01** [comment]
Que bien mae!
